modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="uninfectedzone"
version="${file.jarVersion}"
displayName="Uninfected Zone"
logoFile="uninfectedzone.png"
authors="Love, Cheese and small house plants"
description='''
'''
[[dependencies.uninfectedzone]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.uninfectedzone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"